---
title: "**MINVAL** - **MIN**imal **VAL**idation for Stoichiometric Reactions"
author: "Daniel Osorio, Janneth Gonzalez and Andrés Pinzón-Velasco."
#date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Plotting Random Effects of Mixed Models}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Introduction to MINVAL
The **MINVAL** package was designed as a tool to identify orphan metabolites and evaluate the mass and charge balance of stoichometric reactions. MINVAL also includes functions to write models in TSV and SBML formats, extract all reactants, products, metabolite names and compartments from a metabolic reconstruction.

## Getting started
```{r message=FALSE}
library("minval")
library("sybilSBML")
```

```{r}
glycolysis <- read.csv2(system.file("extdata", "glycolysisKEGG.csv", package = "minval"),
                        stringsAsFactors = FALSE)
colnames(glycolysis)
```

```{r}
glycolysis$REACTION
```

```{r}
isValidSyntax(reactionList = glycolysis$REACTION)
```

```{r}
glycolysis$REACTION[2]
glycolysis$REACTION[2] <- "D-Glyceraldehyde 3-phosphate[c] <=> 3 Glycerone phosphate[c]"
```

```{r}
glycolysis$REACTION[6]
glycolysis$REACTION[6] <- "2-Phospho-D-glycerate[c] <=> 3-Phospho-D-glycerate[c]"
```
```{r}
isValidSyntax(reactionList = glycolysis$REACTION)
```

```{r}
chemicalData <- read.csv2(system.file("extdata", "chemData.csv", package = "minval"))
isBalanced(reactionList = glycolysis$REACTION,referenceData = chemicalData,ids = "NAME",mFormula = "FORMULA")
glycolysis$REACTION[2]
glycolysis$REACTION[2] <- "D-Glyceraldehyde 3-phosphate[c] <=> Glycerone phosphate[c]"
glycolysis$REACTION[8] <- "alpha-D-Glucose 6-phosphate[c] <=> beta-D-Fructose 6-phosphate[c]"
isBalanced(reactionList = glycolysis$REACTION,referenceData = chemicalData,ids = "NAME",mFormula = "FORMULA")
```

```{r}
addExchangeReactions <- function(reconstruction){
  reconstruction <- as.data.frame.array(reconstruction)
  if(all(names(reconstruction)%in%c("ID","DESCRIPTION","REACTION","GPR","LOWER.BOUND","UPPER.BOUND","OBJECTIVE"))){
    orphans <- table(c(orphanReactants(reconstruction[["REACTION"]]),orphanProducts(reconstruction[["REACTION"]])))
    new <- cbind(sapply(names(orphans), function(metabolite){paste0("EX_",metabolites(metabolite,woCompartment = TRUE),"(",compartments(metabolite),")")},USE.NAMES = FALSE),
          sapply(names(orphans), function(metabolite){paste0("Exchange of ", metabolites(metabolite,woCompartment = TRUE))},USE.NAMES = FALSE),
          sapply(names(orphans), function(metabolite){paste0(metabolite," <=>")},USE.NAMES = FALSE),
          sapply(names(orphans), function(metabolite){""},USE.NAMES = FALSE),
          ifelse(names(orphans)%in%orphanReactants(reconstruction[["REACTION"]]),-1000,0),
          ifelse(names(orphans)%in%orphanProducts(reconstruction[["REACTION"]]),1000,0),
          sapply(names(orphans), function(metabolite){0},USE.NAMES = FALSE))
    colnames(new) <- colnames(reconstruction)
    new <- as.data.frame(rbind(reconstruction,new),row.names=NULL)
    return(new)
  } else {
    return(FALSE)
  }
}
g <- addExchangeReactions(glycolysis)
convert2sbml(g,"o.sbml")
```
```{r,warning=FALSE,message=FALSE}
a <- readSBMLmod("o.sbml")
```
```{r}
lowbnd(a)[a@react_id=="EX_alpha_D_Glucose(c)"] <- -1
optimizeProb(a)
```